#include "hooks.h"
#include <stdio.h>

int pre_rebase_hook() {
  FILE *fp = fopen(".hit/hooks/pre-rebase.sample", "w");
  if (fp == NULL) {
    printf("Error: fopen .hit/hooks/pre-rebase.sample\n");
    return -1;
  }
  fprintf(fp, "#!/bin/sh\n"
    "#\n"
    "# Copyright (c) 2006, 2008 Junio C Hamano\n"
    "#\n"
    "# The \"pre-rebase\" hook is run just before \"git rebase\" starts doing\n"
    "# its job, and can prevent the command from running by exiting with\n"
    "# non-zero status.\n"
    "#\n"
    "# The hook is called with the following parameters:\n"
    "#\n"
    "# $1 -- the upstream the series was forked from.\n"
    "# $2 -- the branch being rebased (or empty when rebasing the current branch).\n"
    "#\n"
    "# This sample shows how to prevent topic branches that are already\n"
    "# merged to 'next' branch from getting rebased, because allowing it\n"
    "# would result in rebasing already published history.\n"
    "\n"
    "publish=next\n"
    "basebranch=\"$1\"\n"
    "if test \"$#\" = 2\n"
    "then\n"
    "	topic=\"refs/heads/$2\"\n"
    "else\n"
    "	topic=`git symbolic-ref HEAD` ||\n"
    "	exit 0 ;# we do not interrupt rebasing detached HEAD\n"
    "fi\n"
    "\n"
    "case \"$topic\" in\n"
    "refs/heads/?" "?/*)\n"
    "	;;\n"
    "*)\n"
    "	exit 0 ;# we do not interrupt others.\n"
    "	;;\n"
    "esac\n"
    "\n"
    "# Now we are dealing with a topic branch being rebased\n"
    "# on top of master.  Is it OK to rebase it?\n"
    "\n"
    "# Does the topic really exist?\n"
    "git show-ref -q \"$topic\" || {\n"
    "	echo >&2 \"No such branch $topic\"\n"
    "	exit 1\n"
    "}\n"
    "\n"
    "# Is topic fully merged to master?\n"
    "not_in_master=`git rev-list --pretty=oneline ^master \"$topic\"`\n"
    "if test -z \"$not_in_master\"\n"
    "then\n"
    "	echo >&2 \"$topic is fully merged to master; better remove it.\"\n"
    "	exit 1 ;# we could allow it, but there is no point.\n"
    "fi\n"
    "\n"
    "# Is topic ever merged to next?  If so you should not be rebasing it.\n"
    "only_next_1=`git rev-list ^master \"^$topic\" ${publish} | sort`\n"
    "only_next_2=`git rev-list ^master           ${publish} | sort`\n"
    "if test \"$only_next_1\" = \"$only_next_2\"\n"
    "then\n"
    "	not_in_topic=`git rev-list \"^$topic\" master`\n"
    "	if test -z \"$not_in_topic\"\n"
    "	then\n"
    "		echo >&2 \"$topic is already up to date with master\"\n"
    "		exit 1 ;# we could allow it, but there is no point.\n"
    "	else\n"
    "		exit 0\n"
    "	fi\n"
    "else\n"
    "	not_in_next=`git rev-list --pretty=oneline ^${publish} \"$topic\"`\n"
    "	/usr/bin/perl -e '\n"
    "		my $topic = $ARGV[0];\n"
    "		my $msg = \"* $topic has commits already merged to public branch:\\n\";\n"
    "		my (%%not_in_next) = map {\n"
    "			/^([0-9a-f]+) /;\n"
    "			($1 => 1);\n"
    "		} split(/\\n/, $ARGV[1]);\n"
    "		for my $elem (map {\n"
    "				/^([0-9a-f]+) (.*)$/;\n"
    "				[$1 => $2];\n"
    "			} split(/\\n/, $ARGV[2])) {\n"
    "			if (!exists $not_in_next{$elem->[0]}) {\n"
    "				if ($msg) {\n"
    "					print STDERR $msg;\n"
    "					undef $msg;\n"
    "				}\n"
    "				print STDERR \" $elem->[1]\\n\";\n"
    "			}\n"
    "		}\n"
    "	' \"$topic\" \"$not_in_next\" \"$not_in_master\"\n"
    "	exit 1\n"
    "fi\n"
    "\n"
    "<<\\DOC_END\n"
    "\n"
    "This sample hook safeguards topic branches that have been\n"
    "published from being rewound.\n"
    "\n"
    "The workflow assumed here is:\n"
    "\n"
    " * Once a topic branch forks from \"master\", \"master\" is never\n"
    "   merged into it again (either directly or indirectly).\n"
    "\n"
    " * Once a topic branch is fully cooked and merged into \"master\",\n"
    "   it is deleted.  If you need to build on top of it to correct\n"
    "   earlier mistakes, a new topic branch is created by forking at\n"
    "   the tip of the \"master\".  This is not strictly necessary, but\n"
    "   it makes it easier to keep your history simple.\n"
    "\n"
    " * Whenever you need to test or publish your changes to topic\n"
    "   branches, merge them into \"next\" branch.\n"
    "\n"
    "The script, being an example, hardcodes the publish branch name\n"
    "to be \"next\", but it is trivial to make it configurable via\n"
    "$GIT_DIR/config mechanism.\n"
    "\n"
    "With this workflow, you would want to know:\n"
    "\n"
    "(1) ... if a topic branch has ever been merged to \"next\".  Young\n"
    "    topic branches can have stupid mistakes you would rather\n"
    "    clean up before publishing, and things that have not been\n"
    "    merged into other branches can be easily rebased without\n"
    "    affecting other people.  But once it is published, you would\n"
    "    not want to rewind it.\n"
    "\n"
    "(2) ... if a topic branch has been fully merged to \"master\".\n"
    "    Then you can delete it.  More importantly, you should not\n"
    "    build on top of it -- other people may already want to\n"
    "    change things related to the topic as patches against your\n"
    "    \"master\", so if you need further changes, it is better to\n"
    "    fork the topic (perhaps with the same name) afresh from the\n"
    "    tip of \"master\".\n"
    "\n"
    "Let's look at this example:\n"
    "\n"
    "		   o---o---o---o---o---o---o---o---o---o \"next\"\n"
    "		  /       /           /           /\n"
    "		 /   a---a---b A     /           /\n"
    "		/   /               /           /\n"
    "	       /   /   c---c---c---c B         /\n"
    "	      /   /   /             \\         /\n"
    "	     /   /   /   b---b C     \\       /\n"
    "	    /   /   /   /             \\     /\n"
    "    ---o---o---o---o---o---o---o---o---o---o---o \"master\"\n"
    "\n"
    "\n"
    "A, B and C are topic branches.\n"
    "\n"
    " * A has one fix since it was merged up to \"next\".\n"
    "\n"
    " * B has finished.  It has been fully merged up to \"master\" and \"next\",\n"
    "   and is ready to be deleted.\n"
    "\n"
    " * C has not merged to \"next\" at all.\n"
    "\n"
    "We would want to allow C to be rebased, refuse A, and encourage\n"
    "B to be deleted.\n"
    "\n"
    "To compute (1):\n"
    "\n"
    "	git rev-list ^master ^topic next\n"
    "	git rev-list ^master        next\n"
    "\n"
    "	if these match, topic has not merged in next at all.\n"
    "\n"
    "To compute (2):\n"
    "\n"
    "	git rev-list master..topic\n"
    "\n"
    "	if this is empty, it is fully merged to \"master\".\n"
    "\n"
    "DOC_END\n"
    "");
  fclose(fp);
  return 0;
}
