#include "hooks.h"
#include <stdio.h>

int push_to_checkout_hook() {
  FILE *fp = fopen(".hit/hooks/push-to-checkout.sample", "w");
  if (fp == NULL) {
    printf("Error: fopen .hit/hooks/push-to-checkout.sample\n");
    return -1;
  }
  fprintf(fp, "#!/bin/sh\n"
    "\n"
    "# An example hook script to update a checked-out tree on a git push.\n"
    "#\n"
    "# This hook is invoked by git-receive-pack(1) when it reacts to git\n"
    "# push and updates reference(s) in its repository, and when the push\n"
    "# tries to update the branch that is currently checked out and the\n"
    "# receive.denyCurrentBranch configuration variable is set to\n"
    "# updateInstead.\n"
    "#\n"
    "# By default, such a push is refused if the working tree and the index\n"
    "# of the remote repository has any difference from the currently\n"
    "# checked out commit; when both the working tree and the index match\n"
    "# the current commit, they are updated to match the newly pushed tip\n"
    "# of the branch. This hook is to be used to override the default\n"
    "# behaviour; however the code below reimplements the default behaviour\n"
    "# as a starting point for convenient modification.\n"
    "#\n"
    "# The hook receives the commit with which the tip of the current\n"
    "# branch is going to be updated:\n"
    "commit=$1\n"
    "\n"
    "# It can exit with a non-zero status to refuse the push (when it does\n"
    "# so, it must not modify the index or the working tree).\n"
    "die () {\n"
    "	echo >&2 \"$*\"\n"
    "	exit 1\n"
    "}\n"
    "\n"
    "# Or it can make any necessary changes to the working tree and to the\n"
    "# index to bring them to the desired state when the tip of the current\n"
    "# branch is updated to the new commit, and exit with a zero status.\n"
    "#\n"
    "# For example, the hook can simply run git read-tree -u -m HEAD \"$1\"\n"
    "# in order to emulate git fetch that is run in the reverse direction\n"
    "# with git push, as the two-tree form of git read-tree -u -m is\n"
    "# essentially the same as git switch or git checkout that switches\n"
    "# branches while keeping the local changes in the working tree that do\n"
    "# not interfere with the difference between the branches.\n"
    "\n"
    "# The below is a more-or-less exact translation to shell of the C code\n"
    "# for the default behaviour for git's push-to-checkout hook defined in\n"
    "# the push_to_deploy() function in builtin/receive-pack.c.\n"
    "#\n"
    "# Note that the hook will be executed from the repository directory,\n"
    "# not from the working tree, so if you want to perform operations on\n"
    "# the working tree, you will have to adapt your code accordingly, e.g.\n"
    "# by adding \"cd ..\" or using relative paths.\n"
    "\n"
    "if ! git update-index -q --ignore-submodules --refresh\n"
    "then\n"
    "	die \"Up-to-date check failed\"\n"
    "fi\n"
    "\n"
    "if ! git diff-files --quiet --ignore-submodules --\n"
    "then\n"
    "	die \"Working directory has unstaged changes\"\n"
    "fi\n"
    "\n"
    "# This is a rough translation of:\n"
    "#\n"
    "#   head_has_history() ? \"HEAD\" : EMPTY_TREE_SHA1_HEX\n"
    "if git cat-file -e HEAD 2>/dev/null\n"
    "then\n"
    "	head=HEAD\n"
    "else\n"
    "	head=$(git hash-object -t tree --stdin </dev/null)\n"
    "fi\n"
    "\n"
    "if ! git diff-index --quiet --cached --ignore-submodules $head --\n"
    "then\n"
    "	die \"Working directory has staged changes\"\n"
    "fi\n"
    "\n"
    "if ! git read-tree -u -m \"$commit\"\n"
    "then\n"
    "	die \"Could not update working tree to new HEAD\"\n"
    "fi\n"
    "");
  fclose(fp);
  return 0;
}
