#include "hooks.h"
#include <stdio.h>

int sendemail_validate_hook() {
  FILE *fp = fopen(".hit/hooks/sendemail-validate.sample", "w");
  if (fp == NULL) {
    printf("Error: fopen .hit/hooks/sendemail-validate.sample\n");
    return -1;
  }
  fprintf(fp, "#!/bin/sh\n"
    "\n"
    "# An example hook script to validate a patch (and/or patch series) before\n"
    "# sending it via email.\n"
    "#\n"
    "# The hook should exit with non-zero status after issuing an appropriate\n"
    "# message if it wants to prevent the email(s) from being sent.\n"
    "#\n"
    "# To enable this hook, rename this file to \"sendemail-validate\".\n"
    "#\n"
    "# By default, it will only check that the patch(es) can be applied on top of\n"
    "# the default upstream branch without conflicts in a secondary worktree. After\n"
    "# validation (successful or not) of the last patch of a series, the worktree\n"
    "# will be deleted.\n"
    "#\n"
    "# The following config variables can be set to change the default remote and\n"
    "# remote ref that are used to apply the patches against:\n"
    "#\n"
    "#   sendemail.validateRemote (default: origin)\n"
    "#   sendemail.validateRemoteRef (default: HEAD)\n"
    "#\n"
    "# Replace the TODO placeholders with appropriate checks according to your\n"
    "# needs.\n"
    "\n"
    "validate_cover_letter () {\n"
    "	file=\"$1\"\n"
    "	# TODO: Replace with appropriate checks (e.g. spell checking).\n"
    "	true\n"
    "}\n"
    "\n"
    "validate_patch () {\n"
    "	file=\"$1\"\n"
    "	# Ensure that the patch applies without conflicts.\n"
    "	git am -3 \"$file\" || return\n"
    "	# TODO: Replace with appropriate checks for this patch\n"
    "	# (e.g. checkpatch.pl).\n"
    "	true\n"
    "}\n"
    "\n"
    "validate_series () {\n"
    "	# TODO: Replace with appropriate checks for the whole series\n"
    "	# (e.g. quick build, coding style checks, etc.).\n"
    "	true\n"
    "}\n"
    "\n"
    "# main -------------------------------------------------------------------------\n"
    "\n"
    "if test \"$GIT_SENDEMAIL_FILE_COUNTER\" = 1\n"
    "then\n"
    "	remote=$(git config --default origin --get sendemail.validateRemote) &&\n"
    "	ref=$(git config --default HEAD --get sendemail.validateRemoteRef) &&\n"
    "	worktree=$(mktemp --tmpdir -d sendemail-validate.XXXXXXX) &&\n"
    "	git worktree add -fd --checkout \"$worktree\" \"refs/remotes/$remote/$ref\" &&\n"
    "	git config --replace-all sendemail.validateWorktree \"$worktree\"\n"
    "else\n"
    "	worktree=$(git config --get sendemail.validateWorktree)\n"
    "fi || {\n"
    "	echo \"sendemail-validate: error: failed to prepare worktree\" >&2\n"
    "	exit 1\n"
    "}\n"
    "\n"
    "unset GIT_DIR GIT_WORK_TREE\n"
    "cd \"$worktree\" &&\n"
    "\n"
    "if grep -q \"^diff --git \" \"$1\"\n"
    "then\n"
    "	validate_patch \"$1\"\n"
    "else\n"
    "	validate_cover_letter \"$1\"\n"
    "fi &&\n"
    "\n"
    "if test \"$GIT_SENDEMAIL_FILE_COUNTER\" = \"$GIT_SENDEMAIL_FILE_TOTAL\"\n"
    "then\n"
    "	git config --unset-all sendemail.validateWorktree &&\n"
    "	trap 'git worktree remove -ff \"$worktree\"' EXIT &&\n"
    "	validate_series\n"
    "fi\n"
    "");
  fclose(fp);
  return 0;
}
