#include "hooks.h"
#include <stdio.h>

int fsmonitor_watchman_hook() {
  FILE *fp = fopen(".hit/hooks/fsmonitor-watchman.sample", "w");
  if (fp == NULL) {
    printf("Error: fopen .hit/hooks/fsmonitor-watchman.sample\n");
    return -1;
  }
  fprintf(fp, "#!/usr/bin/perl\n"
    "\n"
    "use strict;\n"
    "use warnings;\n"
    "use IPC::Open2;\n"
    "\n"
    "# An example hook script to integrate Watchman\n"
    "# (https://facebook.github.io/watchman/) with git to speed up detecting\n"
    "# new and modified files.\n"
    "#\n"
    "# The hook is passed a version (currently 2) and last update token\n"
    "# formatted as a string and outputs to stdout a new update token and\n"
    "# all files that have been modified since the update token. Paths must\n"
    "# be relative to the root of the working tree and separated by a single NUL.\n"
    "#\n"
    "# To enable this hook, rename this file to \"query-watchman\" and set\n"
    "# 'git config core.fsmonitor .git/hooks/query-watchman'\n"
    "#\n"
    "my ($version, $last_update_token) = @ARGV;\n"
    "\n"
    "# Uncomment for debugging\n"
    "# print STDERR \"$0 $version $last_update_token\\n\";\n"
    "\n"
    "# Check the hook interface version\n"
    "if ($version ne 2) {\n"
    "	die \"Unsupported query-fsmonitor hook version '$version'.\\n\" .\n"
    "	    \"Falling back to scanning...\\n\";\n"
    "}\n"
    "\n"
    "my $git_work_tree = get_working_dir();\n"
    "\n"
    "my $retry = 1;\n"
    "\n"
    "my $json_pkg;\n"
    "eval {\n"
    "	require JSON::XS;\n"
    "	$json_pkg = \"JSON::XS\";\n"
    "	1;\n"
    "} or do {\n"
    "	require JSON::PP;\n"
    "	$json_pkg = \"JSON::PP\";\n"
    "};\n"
    "\n"
    "launch_watchman();\n"
    "\n"
    "sub launch_watchman {\n"
    "	my $o = watchman_query();\n"
    "	if (is_work_tree_watched($o)) {\n"
    "		output_result($o->{clock}, @{$o->{files}});\n"
    "	}\n"
    "}\n"
    "\n"
    "sub output_result {\n"
    "	my ($clockid, @files) = @_;\n"
    "\n"
    "	# Uncomment for debugging watchman output\n"
    "	# open (my $fh, \">\", \".git/watchman-output.out\");\n"
    "	# binmode $fh, \":utf8\";\n"
    "	# print $fh \"$clockid\\n@files\\n\";\n"
    "	# close $fh;\n"
    "\n"
    "	binmode STDOUT, \":utf8\";\n"
    "	print $clockid;\n"
    "	print \"\\0\";\n"
    "	local $, = \"\\0\";\n"
    "	print @files;\n"
    "}\n"
    "\n"
    "sub watchman_clock {\n"
    "	my $response = qx/watchman clock \"$git_work_tree\"/;\n"
    "	die \"Failed to get clock id on '$git_work_tree'.\\n\" .\n"
    "		\"Falling back to scanning...\\n\" if $? != 0;\n"
    "\n"
    "	return $json_pkg->new->utf8->decode($response);\n"
    "}\n"
    "\n"
    "sub watchman_query {\n"
    "	my $pid = open2(\\*CHLD_OUT, \\*CHLD_IN, 'watchman -j --no-pretty')\n"
    "	or die \"open2() failed: $!\\n\" .\n"
    "	\"Falling back to scanning...\\n\";\n"
    "\n"
    "	# In the query expression below we're asking for names of files that\n"
    "	# changed since $last_update_token but not from the .git folder.\n"
    "	#\n"
    "	# To accomplish this, we're using the \"since\" generator to use the\n"
    "	# recency index to select candidate nodes and \"fields\" to limit the\n"
    "	# output to file names only. Then we're using the \"expression\" term to\n"
    "	# further constrain the results.\n"
    "	my $last_update_line = \"\";\n"
    "	if (substr($last_update_token, 0, 1) eq \"c\") {\n"
    "		$last_update_token = \"\\\"$last_update_token\\\"\";\n"
    "		$last_update_line = qq[\\n\"since\": $last_update_token,];\n"
    "	}\n"
    "	my $query = <<\"	END\";\n"
    "		[\"query\", \"$git_work_tree\", {$last_update_line\n"
    "			\"fields\": [\"name\"],\n"
    "			\"expression\": [\"not\", [\"dirname\", \".git\"]]\n"
    "		}]\n"
    "	END\n"
    "\n"
    "	# Uncomment for debugging the watchman query\n"
    "	# open (my $fh, \">\", \".git/watchman-query.json\");\n"
    "	# print $fh $query;\n"
    "	# close $fh;\n"
    "\n"
    "	print CHLD_IN $query;\n"
    "	close CHLD_IN;\n"
    "	my $response = do {local $/; <CHLD_OUT>};\n"
    "\n"
    "	# Uncomment for debugging the watch response\n"
    "	# open ($fh, \">\", \".git/watchman-response.json\");\n"
    "	# print $fh $response;\n"
    "	# close $fh;\n"
    "\n"
    "	die \"Watchman: command returned no output.\\n\" .\n"
    "	\"Falling back to scanning...\\n\" if $response eq \"\";\n"
    "	die \"Watchman: command returned invalid output: $response\\n\" .\n"
    "	\"Falling back to scanning...\\n\" unless $response =~ /^\\{/;\n"
    "\n"
    "	return $json_pkg->new->utf8->decode($response);\n"
    "}\n"
    "\n"
    "sub is_work_tree_watched {\n"
    "	my ($output) = @_;\n"
    "	my $error = $output->{error};\n"
    "	if ($retry > 0 and $error and $error =~ m/unable to resolve root .* directory (.*) is not watched/) {\n"
    "		$retry--;\n"
    "		my $response = qx/watchman watch \"$git_work_tree\"/;\n"
    "		die \"Failed to make watchman watch '$git_work_tree'.\\n\" .\n"
    "		    \"Falling back to scanning...\\n\" if $? != 0;\n"
    "		$output = $json_pkg->new->utf8->decode($response);\n"
    "		$error = $output->{error};\n"
    "		die \"Watchman: $error.\\n\" .\n"
    "		\"Falling back to scanning...\\n\" if $error;\n"
    "\n"
    "		# Uncomment for debugging watchman output\n"
    "		# open (my $fh, \">\", \".git/watchman-output.out\");\n"
    "		# close $fh;\n"
    "\n"
    "		# Watchman will always return all files on the first query so\n"
    "		# return the fast \"everything is dirty\" flag to git and do the\n"
    "		# Watchman query just to get it over with now so we won't pay\n"
    "		# the cost in git to look up each individual file.\n"
    "		my $o = watchman_clock();\n"
    "		$error = $output->{error};\n"
    "\n"
    "		die \"Watchman: $error.\\n\" .\n"
    "		\"Falling back to scanning...\\n\" if $error;\n"
    "\n"
    "		output_result($o->{clock}, (\"/\"));\n"
    "		$last_update_token = $o->{clock};\n"
    "\n"
    "		eval { launch_watchman() };\n"
    "		return 0;\n"
    "	}\n"
    "\n"
    "	die \"Watchman: $error.\\n\" .\n"
    "	\"Falling back to scanning...\\n\" if $error;\n"
    "\n"
    "	return 1;\n"
    "}\n"
    "\n"
    "sub get_working_dir {\n"
    "	my $working_dir;\n"
    "	if ($^O =~ 'msys' || $^O =~ 'cygwin') {\n"
    "		$working_dir = Win32::GetCwd();\n"
    "		$working_dir =~ tr/\\\\/\\//;\n"
    "	} else {\n"
    "		require Cwd;\n"
    "		$working_dir = Cwd::cwd();\n"
    "	}\n"
    "\n"
    "	return $working_dir;\n"
    "}\n"
    "");
  fclose(fp);
  return 0;
}
