#include "hooks.h"
#include <stdio.h>

int update_hook() {
  FILE *fp = fopen(".hit/hooks/update.sample", "w");
  if (fp == NULL) {
    printf("Error: fopen .hit/hooks/update.sample\n");
    return -1;
  }
  fprintf(fp, "#!/bin/sh\n"
    "#\n"
    "# An example hook script to block unannotated tags from entering.\n"
    "# Called by \"git receive-pack\" with arguments: refname sha1-old sha1-new\n"
    "#\n"
    "# To enable this hook, rename this file to \"update\".\n"
    "#\n"
    "# Config\n"
    "# ------\n"
    "# hooks.allowunannotated\n"
    "#   This boolean sets whether unannotated tags will be allowed into the\n"
    "#   repository.  By default they won't be.\n"
    "# hooks.allowdeletetag\n"
    "#   This boolean sets whether deleting tags will be allowed in the\n"
    "#   repository.  By default they won't be.\n"
    "# hooks.allowmodifytag\n"
    "#   This boolean sets whether a tag may be modified after creation. By default\n"
    "#   it won't be.\n"
    "# hooks.allowdeletebranch\n"
    "#   This boolean sets whether deleting branches will be allowed in the\n"
    "#   repository.  By default they won't be.\n"
    "# hooks.denycreatebranch\n"
    "#   This boolean sets whether remotely creating branches will be denied\n"
    "#   in the repository.  By default this is allowed.\n"
    "#\n"
    "\n"
    "# --- Command line\n"
    "refname=\"$1\"\n"
    "oldrev=\"$2\"\n"
    "newrev=\"$3\"\n"
    "\n"
    "# --- Safety check\n"
    "if [ -z \"$GIT_DIR\" ]; then\n"
    "	echo \"Don't run this script from the command line.\" >&2\n"
    "	echo \" (if you want, you could supply GIT_DIR then run\" >&2\n"
    "	echo \"  $0 <ref> <oldrev> <newrev>)\" >&2\n"
    "	exit 1\n"
    "fi\n"
    "\n"
    "if [ -z \"$refname\" -o -z \"$oldrev\" -o -z \"$newrev\" ]; then\n"
    "	echo \"usage: $0 <ref> <oldrev> <newrev>\" >&2\n"
    "	exit 1\n"
    "fi\n"
    "\n"
    "# --- Config\n"
    "allowunannotated=$(git config --type=bool hooks.allowunannotated)\n"
    "allowdeletebranch=$(git config --type=bool hooks.allowdeletebranch)\n"
    "denycreatebranch=$(git config --type=bool hooks.denycreatebranch)\n"
    "allowdeletetag=$(git config --type=bool hooks.allowdeletetag)\n"
    "allowmodifytag=$(git config --type=bool hooks.allowmodifytag)\n"
    "\n"
    "# check for no description\n"
    "projectdesc=$(sed -e '1q' \"$GIT_DIR/description\")\n"
    "case \"$projectdesc\" in\n"
    "\"Unnamed repository\"* | \"\")\n"
    "	echo \"*** Project description file hasn't been set\" >&2\n"
    "	exit 1\n"
    "	;;\n"
    "esac\n"
    "\n"
    "# --- Check types\n"
    "# if $newrev is 0000...0000, it's a commit to delete a ref.\n"
    "zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')\n"
    "if [ \"$newrev\" = \"$zero\" ]; then\n"
    "	newrev_type=delete\n"
    "else\n"
    "	newrev_type=$(git cat-file -t $newrev)\n"
    "fi\n"
    "\n"
    "case \"$refname\",\"$newrev_type\" in\n"
    "	refs/tags/*,commit)\n"
    "		# un-annotated tag\n"
    "		short_refname=${refname##refs/tags/}\n"
    "		if [ \"$allowunannotated\" != \"true\" ]; then\n"
    "			echo \"*** The un-annotated tag, $short_refname, is not allowed in this repository\" >&2\n"
    "			echo \"*** Use 'git tag [ -a | -s ]' for tags you want to propagate.\" >&2\n"
    "			exit 1\n"
    "		fi\n"
    "		;;\n"
    "	refs/tags/*,delete)\n"
    "		# delete tag\n"
    "		if [ \"$allowdeletetag\" != \"true\" ]; then\n"
    "			echo \"*** Deleting a tag is not allowed in this repository\" >&2\n"
    "			exit 1\n"
    "		fi\n"
    "		;;\n"
    "	refs/tags/*,tag)\n"
    "		# annotated tag\n"
    "		if [ \"$allowmodifytag\" != \"true\" ] && git rev-parse $refname > /dev/null 2>&1\n"
    "		then\n"
    "			echo \"*** Tag '$refname' already exists.\" >&2\n"
    "			echo \"*** Modifying a tag is not allowed in this repository.\" >&2\n"
    "			exit 1\n"
    "		fi\n"
    "		;;\n"
    "	refs/heads/*,commit)\n"
    "		# branch\n"
    "		if [ \"$oldrev\" = \"$zero\" -a \"$denycreatebranch\" = \"true\" ]; then\n"
    "			echo \"*** Creating a branch is not allowed in this repository\" >&2\n"
    "			exit 1\n"
    "		fi\n"
    "		;;\n"
    "	refs/heads/*,delete)\n"
    "		# delete branch\n"
    "		if [ \"$allowdeletebranch\" != \"true\" ]; then\n"
    "			echo \"*** Deleting a branch is not allowed in this repository\" >&2\n"
    "			exit 1\n"
    "		fi\n"
    "		;;\n"
    "	refs/remotes/*,commit)\n"
    "		# tracking branch\n"
    "		;;\n"
    "	refs/remotes/*,delete)\n"
    "		# delete tracking branch\n"
    "		if [ \"$allowdeletebranch\" != \"true\" ]; then\n"
    "			echo \"*** Deleting a tracking branch is not allowed in this repository\" >&2\n"
    "			exit 1\n"
    "		fi\n"
    "		;;\n"
    "	*)\n"
    "		# Anything else (is there anything else?)\n"
    "		echo \"*** Update hook: unknown type of update to ref $refname of type $newrev_type\" >&2\n"
    "		exit 1\n"
    "		;;\n"
    "esac\n"
    "\n"
    "# --- Finished\n"
    "exit 0\n"
    "");
  fclose(fp);
  return 0;
}
