on:
  workflow_call:

jobs:
  mem-check:
    name: memory check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: build
        run: mkdir build && cd build && cmake .. && make

      - name: mem-check
        run: valgrind --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=definite ./build/hit